#!/bin/bash
if `st $@ > /dev/null` ; then
    p=`st $@ -p`
    folder=`st $@`
    if echo "$folder" | wc -l | grep '[ ]1$' -q ; then
        if echo "$folder" | grep ^/ -q ; then
          cd "$folder"
        else
          cd "$p/$folder"
        fi
    else
        cd "$p"
    fi
fi
