#!/bin/bash
kw="$@"
if [ -z "$kw" ] ; then
  find . | st --
else
  result="`find . -iregex ".*$kw.*" | sort -V`"
  echo "$result" | st -- > /dev/null
  st - | grep -i $kw --colour=always | st -- -b temp
  st -C -b temp
fi
