#!/bin/bash
ignore='-i'
if [ "$1" == "-C" ] ; then
  ignore=
  shift
fi

generated='\.generated\.'
if [ "$1" == "-g" ] ; then
    generated='$^'
    shift
fi

key="$1"
shift

case $# in
  0) domain=(.) ;;
  *) domain=("$@") ;;
esac

grep "$key" $ignore -bnrI "${domain[@]}" | grep -v "$generated" | st -- > /dev/null

st - | vimgrepcolorizer grep $ignore --colour=always "$key" | st -- -s -b temp
st - | cut -f 1 -d : | st -- > /dev/null

