#!/bin/bash
ignore='-i'
if [ "$1" == "-C" ] ; then
  ignore=
  shift
fi

key="$1"
shift

case $# in
  0) domain=(.) ;;
  *) domain=("$@") ;;
esac

grep "$key" $ignore -nrI "$domain" | st -- > /dev/null

fmt='{ printf "\x1b[35m" $1 "\x1b[32m" $2 "\x1b[0m "'
fmt="$fmt ; for (i=3; i<=NF; i++) printf \$i \" \" ; printf \"\n\"}"
st - | sed 's/:/: /' | sed 's/:/: /2' | \
  awk "$fmt" | grep $ignore --colour=always "$key" | st -- -s -b temp
st - | cut -f 1 -d : | st -- > /dev/null

