#!/bin/bash
lsOpt=()
kw=""
for opt in "$@" ; do
  if echo "$opt" | grep "^-" -q ; then
    lsOpt+=("$opt")
  else
    kw="$opt"
  fi
done
result="`ls "${lsOpt[@]}" | sort -V`"
resultColored="`CLICOLOR_FORCE=1 ls -G "${lsOpt[@]}" | sort -V`"
if [ -z "$kw" ] ; then
  echo "$resultColored" | st --
  echo "$result" | st -- > /dev/null
else
  echo "$result" | grep -i "$kw" --colour=always | st --
  echo "$result" | grep -i "$kw" | st -- > /dev/null
fi
