#!/bin/bash
lsOpt=()
kw=""
for opt in "$@" ; do
  if echo "$opt" | grep "^-" -q ; then
    lsOpt+=("$opt")
  else
    kw="$opt"
  fi
done
result=`ls "${lsOpt[@]}"`
if [ -z "$kw" ] ; then
  echo "$result" | st --
else
  echo "$result" | grep -i "$kw" | st -- | grep -i "$kw" --colour
fi
